mondo/urls.py
from django.conf.urls import url


urlpatterns = (
    url(r'^authorize/$', 'mondo.views.authorize_view', name='authorize'),
    url(r'^logout/$', 'mondo.views.logout_view', name='logout'),
    url(r'^deactivate/$', 'mondo.views.deactivate_view', name='deactivate'),
    url(r'^address/add/$', 'mondo.views.address_add_view', name='address_add'),
    url(r'^address/remove/$', 'mondo.views.address_remove_view', name='address_remove'),
    url(r'^$', 'mondo.views.home_view', name='home'),

)

urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('mondo.urls', namespace='mondo')),
]

bootstrap/models.py
from django.db import models

# Create your models here.

mondo/models.py
from django.db import models
from django.conf import settings

from libbitmondo import BitMondoClient
from libmondo import MondoSessionClient, MondoOauthClient
from libbitcoin import satoshi_to_btc


mondo_client = MondoOauthClient(
    settings.MONDO_AUTH_URL,
    settings.MONDO_API_URL,
    settings.MONDO_CLIENT_ID,
    settings.MONDO_CLIENT_SECRET,
    settings.MONDO_REDIRECT_URL,
)


class MondoAccount(models.Model):
    username = models.CharField(max_length=64)
    token = models.CharField(max_length=256)
    account_id = models.CharField(max_length=64)

    def __unicode__(self):
        return u'%s' % self.username


class BitcoinAddress(models.Model):
    account = models.ForeignKey(MondoAccount)
    address = models.CharField(max_length=40)
    last_balance = models.IntegerField()

    def __unicode__(self):
        return u'%s %s %s' % (self.account, self.address, self.last_balance)

    def send_notification(self, balance, tx_id):
        change = satoshi_to_btc(balance - self.last_balance)
        mondo_session = MondoSessionClient(mondo_client, self.account.token)
        bitmondo = BitMondoClient(mondo_session, self.account.account_id)
        if change > 0:
            bitmondo.incoming_payment(change, self.address, tx_id)
        else:
            bitmondo.outgoing_payment(-change, self.address, tx_id)

mondo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.conf import settings
from django.core.urlresolvers import reverse

from libmondo import MondoOauthClient, MondoSessionClient
from libbitmondo import BitMondoClient
from libbitcoin import get_balance

from mondo.models import MondoAccount, BitcoinAddress


mondo_client = MondoOauthClient(
    settings.MONDO_AUTH_URL,
    settings.MONDO_API_URL,
    settings.MONDO_CLIENT_ID,
    settings.MONDO_CLIENT_SECRET,
    settings.MONDO_REDIRECT_URL,
)


def home_view(request):
    if request.session.get('account_id'):
        account = MondoAccount.objects.get(id=request.session.get('account_id'))
    else:
        account = None

    addresses = []
    if account:
        addresses = account.bitcoinaddress_set.all()

    return render(request, 'home.html', {
        'mondo_auth_url': mondo_client.get_auth_link('somerandom'),
        'account': account,
        'addresses': addresses,
    })


def authorize_view(request):
    token = mondo_client.get_token(request.GET['code'])
    mondo_session = MondoSessionClient(mondo_client, token)
    account_id = mondo_session.get_accounts()['accounts'][0]['id']

    account, created = MondoAccount.objects.get_or_create(
        username='ondrejsika@ondrejsika.com',
        # token=token,
        account_id=account_id,
    )
    account.token = token
    account.save()
    request.session['account_id'] = account.id
    return HttpResponseRedirect(reverse('mondo:home'))


def logout_view(request):
    del request.session['account_id']
    return HttpResponseRedirect(reverse('mondo:home'))


def deactivate_view(request):
    account, created = MondoAccount.objects.get_or_create(
        id=request.session['account_id'],
    )
    account.bitcoinaddress_set.all().delete()
    account.delete()

    del request.session['account_id']
    return HttpResponseRedirect(reverse('mondo:home'))


def address_add_view(request):
    account = MondoAccount.objects.get(id=request.session.get('account_id'))

    raw_address = request.POST.get('address')
    address, created = BitcoinAddress.objects.get_or_create(account=account, address=raw_address,
                                                            last_balance=get_balance(raw_address))
    address.save()
    return HttpResponseRedirect(reverse('mondo:home'))


def address_remove_view(request):
    account = MondoAccount.objects.get(id=request.session.get('account_id'))

    raw_address = request.GET.get('address')
    address = BitcoinAddress.objects.get(account=account, address=raw_address)
    address.delete()
    return HttpResponseRedirect(reverse('mondo:home'))

bootstrap/templates/bootstrap/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
  </head>

  <body>
    {% block body %}{% endblock %}
  </body>
</html>

mondo/templates/base.html
{% extends 'bootstrap/base.html' %}
{% load staticfiles %}
{% block title %}BitMondo{% endblock %}
{% block body %}
    <style>
    body {
      background: url({% static 'bg2.jpg' %}) no-repeat center center fixed;
      -webkit-background-size: cover;
      -moz-background-size: cover;
      -o-background-size: cover;
      background-size: cover;
    }
    </style>
    <div class="container" style="margin-top: 10px; padding-top: 5px; max-width: 730px; background: white; opacity: 0.86; -webkit-border-radius: 5px;-moz-border-radius: 5px;border-radius: 5px;">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills pull-right">
              {% if request.session.account_id %}
                  <li role="presentation">
                    <p class="navbar-text" style="margin-top: 10px"><b>{{ account.username }}</b></p>
                  </li>
                  <li role="presentation"><a href="{% url 'mondo:logout' %}">logout</a></li>
                  <li role="presentation"><a href="{% url 'mondo:deactivate' %}">deactivate</a></li>
              {% else %}
                  <li role="presentation"><a href="{{ mondo_auth_url }}">Login</a></li>
              {% endif %}
          </ul>
        </nav>
        <h3 class="text-muted" style="margin-top: 10px">BitMondo</h3>
      </div>

      <div class="jumbotron">
          {% block content %}{% endblock content %}
      </div>


      <footer class="footer">
        <p>By <a target="_blank" href="https://ondrejsika.com">Ondrej Sika</a> with <span class="glyphicon glyphicon-heart" aria-hidden="true"></span> at <b>London</b></p>
      </footer>

    </div> <!-- /container -->
{% endblock body %}

mondo/templates/home.html
{% extends 'base.html' %}
{% block content %}
    {% if request.session.account_id %}
        <table class="table">
            <tr>
                <form class="form-inline" method="post" action="{% url 'mondo:address_add' %}">
                    {% csrf_token %}
                    <td><input type="text" class="form-control" id="exampleInputName2" placeholder="Bitcoin address" name="address"></td>
                    <td><button type="submit" class="btn btn-success">Add Bitcoin address</button></td>
                </form>
            </tr>
            {% for address in addresses %}
            <tr>
                <td>{{ address.address }}</td>
                <td><a href="{% url 'mondo:address_remove' %}?address={{ address.address }}" class="btn btn-danger">Remove Bitcoin address</a></td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <center><a class="btn btn-lg btn-success" href="{{ mondo_auth_url }}" role="button">Login</a></center>
    {% endif %}
{% endblock content %}